

#define BAUD 9600
#define IS_ABSOLUTE_ADDR 0
#define POSITION_ADDR 1 //2 Bytes
#define COMMAND_IS_MOVING "IM#"
#define COMMANDIS_MOVING_TRUE "IMT#"
#define COMMANDIS_MOVING_FALSE "IMF#"
#define COMMAND_MAX_INCREMENT "MI#"
#define COMMAND_MAX_STEP "MS#"
#define COMMAND_STEP_SIZE "SS#"
#define COMMAND_HALT "H#"
#define COMMAND_SET_ABSOLUTE "SA#"
#define COMMAND_SET_RELATIVE "SR#"
#define COMMAND_IS_ABSOLUTE "IA#"
#define COMMAND_INIT_POSITION "IP#"
#define COMMAND_SAVE_POSITION "SP#"
#define COMMAND_MOVE_IN "MI"
#define COMMAND_MOVE_OUT "MO"
#define COMMAND_MOVE_TO "MT"

